name: Merge to develop CI

on:
  push:
    branches: [develop]

jobs:
  build_tests:
    name: Set up
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Build
        run: npm run build
